name: Deploy do Meu Projeto DevOps

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  validacao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Smoke Test
        run: test -f index.html

      - name: Versão do Ubuntu
        run: lsb_release -a

      - name: Memória do Runner
        run: free -h

      - name: Processadores do Runner
        run: nproc


  ferramenta:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Testar Cowsay
        run: cowsay "Olá DevOps!"

  deploy:
    needs: validacao
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurando Pages
        uses: actions/configure-pages@v5

      - name: Preparando Artefato
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'

      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4