name: Deploy do Meu Projeto DevOps

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  validacao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Smoke Test
        run: test -f index.html

      - name: Explorando o Runner
        run: lsb_release -a && free -h && nproc

      - name: Preparando Artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: validacao
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4